media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: layers
    label: Layers
    type: file
    path: 'content/layers.json'
    fields:
      - name: name
        type: string
      - name: source
        type: string